# Generated by Django 4.1.2 on 2022-12-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='organization',
        ),
    ]
